# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='webpage',
            field=models.URLField(blank=True),
        ),
    ]
