# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-03 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='user_profile_images'),
        ),
    ]
