# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 15:41
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trimit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='specialities',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_limit=5, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', space_delimiter=False, to='trimit.Specialities', verbose_name_plural='Specialities', verbose_name_singular='Speciality'),
        ),
    ]
