# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trimit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.DecimalField(decimal_places=1, default='rating', max_digits=10)),
                ('atmosphere_rating', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('price_rating', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('service_rating', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='page',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='page',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='page',
            name='location',
            field=models.CharField(default='location', max_length=30),
        ),
        migrations.AddField(
            model_name='page',
            name='opening_times',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, upload_to='hairpage_images'),
        ),
        migrations.AddField(
            model_name='page',
            name='specialities',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.OneToOneField(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hairpicture',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='user_profile_images'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='review',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trimit.Page'),
        ),
        migrations.AddField(
            model_name='review',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trimit.UserProfile'),
        ),
    ]
