# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
