# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimit', '0002_page_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=9, null=True),
        ),
    ]
