# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimit', '0002_auto_20190307_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(related_name='favourited', to='trimit.Page'),
        ),
    ]
