# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trimit.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trimit', '0002_auto_20190220_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='user', on_delete=models.SET(trimit.models.deleted_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
