# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimit', '0003_userprofile_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='overall_rating',
        ),
        migrations.AddField(
            model_name='page',
            name='number_of_reviews',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='page',
            name='overall_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='review',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='atmosphere_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='price_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='service_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
