# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import trimit.models


class Migration(migrations.Migration):

    dependencies = [
        ('trimit', '0003_auto_20190220_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=models.SET(trimit.models.deleted_user), on_delete=models.SET(trimit.models.deleted_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
