# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimit', '0006_auto_20190309_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='profile_picture',
            field=models.ImageField(blank=True, default='DefaultPagePic.png', upload_to='user_profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='DefaultUserPic.png', upload_to='user_profile_images'),
        ),
    ]
